// Mocks generated by Mockito 5.4.6 from annotations
// in mengdie/test/summary_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i15;

import 'package:mengdie/app/providers/chat_state/chat_state_notifier.dart'
    as _i12;
import 'package:mengdie/app/providers/chat_state/special_action_type.dart'
    as _i16;
import 'package:mengdie/app/providers/chat_state_providers.dart' as _i5;
import 'package:mengdie/app/repositories/chat_repository.dart' as _i11;
import 'package:mengdie/app/tools/context_xml_service.dart' as _i4;
import 'package:mengdie/data/llmapi/llm_models.dart' as _i3;
import 'package:mengdie/data/llmapi/llm_service.dart' as _i9;
import 'package:mengdie/domain/models/models.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:riverpod/src/framework.dart' as _i2;
import 'package:riverpod/src/internals.dart' as _i7;
import 'package:shared_preferences/shared_preferences.dart' as _i14;
import 'package:state_notifier/state_notifier.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeepAliveLink_1 extends _i1.SmartFake implements _i2.KeepAliveLink {
  _FakeKeepAliveLink_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_2<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlmResponse_3 extends _i1.SmartFake implements _i3.LlmResponse {
  _FakeLlmResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlmImageResponse_4 extends _i1.SmartFake
    implements _i3.LlmImageResponse {
  _FakeLlmImageResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiRequestContext_5 extends _i1.SmartFake
    implements _i4.ApiRequestContext {
  _FakeApiRequestContext_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContextPredictionResult_6 extends _i1.SmartFake
    implements _i4.ContextPredictionResult {
  _FakeContextPredictionResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRef_7<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatScreenState_8 extends _i1.SmartFake
    implements _i5.ChatScreenState {
  _FakeChatScreenState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiConfig_9 extends _i1.SmartFake implements _i6.ApiConfig {
  _FakeApiConfig_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_10 extends _i1.SmartFake implements _i6.Message {
  _FakeMessage_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProviderRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderRef<State> extends _i1.Mock
    implements _i7.ProviderRef<State> {
  MockProviderRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  State get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i8.dummyValue<State>(this, Invocation.getter(#state)),
          )
          as State);

  @override
  set state(State? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i2.ProviderContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeProviderContainer_0(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(State?, State)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateSelf() => super.noSuchMethod(
    Invocation.method(#invalidateSelf, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onAddListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onRemoveListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onResume, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onCancel, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onDispose, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
          )
          as bool);

  @override
  T watch<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  _i2.KeepAliveLink keepAlive() =>
      (super.noSuchMethod(
            Invocation.method(#keepAlive, []),
            returnValue: _FakeKeepAliveLink_1(
              this,
              Invocation.method(#keepAlive, []),
            ),
          )
          as _i2.KeepAliveLink);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_2<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i2.ProviderSubscription<T>);
}

/// A class which mocks [LlmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlmService extends _i1.Mock implements _i9.LlmService {
  MockLlmService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i3.LlmStreamChunk> sendMessageStream({
    required List<_i3.LlmContent>? llmContext,
    required _i6.ApiConfig? apiConfig,
    bool? requestThoughts = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageStream, [], {
              #llmContext: llmContext,
              #apiConfig: apiConfig,
              #requestThoughts: requestThoughts,
            }),
            returnValue: _i10.Stream<_i3.LlmStreamChunk>.empty(),
          )
          as _i10.Stream<_i3.LlmStreamChunk>);

  @override
  _i10.Future<_i3.LlmResponse> sendMessageOnce({
    required List<_i3.LlmContent>? llmContext,
    required _i6.ApiConfig? apiConfig,
    bool? requestThoughts = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageOnce, [], {
              #llmContext: llmContext,
              #apiConfig: apiConfig,
              #requestThoughts: requestThoughts,
            }),
            returnValue: _i10.Future<_i3.LlmResponse>.value(
              _FakeLlmResponse_3(
                this,
                Invocation.method(#sendMessageOnce, [], {
                  #llmContext: llmContext,
                  #apiConfig: apiConfig,
                  #requestThoughts: requestThoughts,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.LlmResponse>);

  @override
  _i10.Future<int> countTokens({
    required List<_i3.LlmContent>? llmContext,
    required _i6.ApiConfig? apiConfig,
    bool? useRemoteCounter = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countTokens, [], {
              #llmContext: llmContext,
              #apiConfig: apiConfig,
              #useRemoteCounter: useRemoteCounter,
            }),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<_i3.LlmImageResponse> generateImage({
    required List<_i3.LlmContent>? llmContext,
    required _i6.ApiConfig? apiConfig,
    int? n = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateImage, [], {
              #llmContext: llmContext,
              #apiConfig: apiConfig,
              #n: n,
            }),
            returnValue: _i10.Future<_i3.LlmImageResponse>.value(
              _FakeLlmImageResponse_4(
                this,
                Invocation.method(#generateImage, [], {
                  #llmContext: llmContext,
                  #apiConfig: apiConfig,
                  #n: n,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.LlmImageResponse>);

  @override
  _i10.Future<void> cancelActiveRequest() =>
      (super.noSuchMethod(
            Invocation.method(#cancelActiveRequest, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i11.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i6.Chat>> getAllChats() =>
      (super.noSuchMethod(
            Invocation.method(#getAllChats, []),
            returnValue: _i10.Future<List<_i6.Chat>>.value(<_i6.Chat>[]),
          )
          as _i10.Future<List<_i6.Chat>>);

  @override
  _i10.Future<_i6.Chat?> getChat(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChat, [chatId]),
            returnValue: _i10.Future<_i6.Chat?>.value(),
          )
          as _i10.Future<_i6.Chat?>);

  @override
  _i10.Future<int> saveChat(_i6.Chat? chat) =>
      (super.noSuchMethod(
            Invocation.method(#saveChat, [chat]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> addFolder({
    required String? title,
    bool? isTemplate = false,
    int? parentFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFolder, [], {
              #title: title,
              #isTemplate: isTemplate,
              #parentFolderId: parentFolderId,
            }),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<bool> deleteChat(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [chatId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<int> deleteChats(List<int>? chatIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChats, [chatIds]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<_i6.Chat>> getChatsInFolder(int? parentFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatsInFolder, [parentFolderId]),
            returnValue: _i10.Future<List<_i6.Chat>>.value(<_i6.Chat>[]),
          )
          as _i10.Future<List<_i6.Chat>>);

  @override
  _i10.Future<void> updateChatOrder(List<_i6.Chat>? chatsToUpdate) =>
      (super.noSuchMethod(
            Invocation.method(#updateChatOrder, [chatsToUpdate]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> moveChatsToNewParent({
    required List<int>? chatIds,
    required int? newParentFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveChatsToNewParent, [], {
              #chatIds: chatIds,
              #newParentFolderId: newParentFolderId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Stream<List<_i6.Chat>> watchChatsInFolder(int? parentFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#watchChatsInFolder, [parentFolderId]),
            returnValue: _i10.Stream<List<_i6.Chat>>.empty(),
          )
          as _i10.Stream<List<_i6.Chat>>);

  @override
  _i10.Stream<_i6.Chat?> watchChat(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#watchChat, [chatId]),
            returnValue: _i10.Stream<_i6.Chat?>.empty(),
          )
          as _i10.Stream<_i6.Chat?>);

  @override
  _i10.Stream<List<_i6.Chat>> watchChatsForUser(
    int? userId,
    int? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchChatsForUser, [userId, parentFolderId]),
            returnValue: _i10.Stream<List<_i6.Chat>>.empty(),
          )
          as _i10.Stream<List<_i6.Chat>>);

  @override
  _i10.Future<int> importChat(_i6.Chat? chat, {int? parentFolderId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #importChat,
              [chat],
              {#parentFolderId: parentFolderId},
            ),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> createChatFromTemplate(
    int? templateChatId, {
    int? parentFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatFromTemplate,
              [templateChatId],
              {#parentFolderId: parentFolderId},
            ),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> duplicateChat(
    int? sourceChatId, {
    int? upToMessageId,
    bool? asTemplate = false,
    bool? shouldClearSummary = true,
    int? targetFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #duplicateChat,
              [sourceChatId],
              {
                #upToMessageId: upToMessageId,
                #asTemplate: asTemplate,
                #shouldClearSummary: shouldClearSummary,
                #targetFolderId: targetFolderId,
              },
            ),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);
}

/// A class which mocks [ContextXmlService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextXmlService extends _i1.Mock implements _i4.ContextXmlService {
  MockContextXmlService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.ApiRequestContext> buildApiRequestContext({
    required int? chatId,
    required _i6.Message? currentUserMessage,
    String? lastMessageOverride,
    int? messageIdToPreserveXml,
    String? chatSystemPromptOverride,
    bool? keepAsSystemPrompt,
    List<_i6.Message>? historyOverride,
    bool? isPrediction = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildApiRequestContext, [], {
              #chatId: chatId,
              #currentUserMessage: currentUserMessage,
              #lastMessageOverride: lastMessageOverride,
              #messageIdToPreserveXml: messageIdToPreserveXml,
              #chatSystemPromptOverride: chatSystemPromptOverride,
              #keepAsSystemPrompt: keepAsSystemPrompt,
              #historyOverride: historyOverride,
              #isPrediction: isPrediction,
            }),
            returnValue: _i10.Future<_i4.ApiRequestContext>.value(
              _FakeApiRequestContext_5(
                this,
                Invocation.method(#buildApiRequestContext, [], {
                  #chatId: chatId,
                  #currentUserMessage: currentUserMessage,
                  #lastMessageOverride: lastMessageOverride,
                  #messageIdToPreserveXml: messageIdToPreserveXml,
                  #chatSystemPromptOverride: chatSystemPromptOverride,
                  #keepAsSystemPrompt: keepAsSystemPrompt,
                  #historyOverride: historyOverride,
                  #isPrediction: isPrediction,
                }),
              ),
            ),
          )
          as _i10.Future<_i4.ApiRequestContext>);

  @override
  _i10.Future<_i4.ContextPredictionResult> predictContextUsage({
    required int? chatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#predictContextUsage, [], {#chatId: chatId}),
            returnValue: _i10.Future<_i4.ContextPredictionResult>.value(
              _FakeContextPredictionResult_6(
                this,
                Invocation.method(#predictContextUsage, [], {#chatId: chatId}),
              ),
            ),
          )
          as _i10.Future<_i4.ContextPredictionResult>);
}

/// A class which mocks [ChatStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatStateNotifier extends _i1.Mock implements _i12.ChatStateNotifier {
  MockChatStateNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_7<Object?>(this, Invocation.getter(#ref)),
          )
          as _i2.Ref<Object?>);

  @override
  int get chatId =>
      (super.noSuchMethod(Invocation.getter(#chatId), returnValue: 0) as int);

  @override
  bool get isFinalizing =>
      (super.noSuchMethod(Invocation.getter(#isFinalizing), returnValue: false)
          as bool);

  @override
  set llmStreamSubscription(
    _i10.StreamSubscription<_i3.LlmStreamChunk>? _llmStreamSubscription,
  ) => super.noSuchMethod(
    Invocation.setter(#llmStreamSubscription, _llmStreamSubscription),
    returnValueForMissingStub: null,
  );

  @override
  set isFinalizing(bool? _isFinalizing) => super.noSuchMethod(
    Invocation.setter(#isFinalizing, _isFinalizing),
    returnValueForMissingStub: null,
  );

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i10.Stream<_i5.ChatScreenState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i5.ChatScreenState>.empty(),
          )
          as _i10.Stream<_i5.ChatScreenState>);

  @override
  _i5.ChatScreenState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeChatScreenState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.ChatScreenState);

  @override
  _i5.ChatScreenState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeChatScreenState_8(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i5.ChatScreenState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i13.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i5.ChatScreenState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  set topMessageTimer(_i10.Timer? _topMessageTimer) => super.noSuchMethod(
    Invocation.setter(#topMessageTimer, _topMessageTimer),
    returnValueForMissingStub: null,
  );

  @override
  set updateTimer(_i10.Timer? _updateTimer) => super.noSuchMethod(
    Invocation.setter(#updateTimer, _updateTimer),
    returnValueForMissingStub: null,
  );

  @override
  _i6.ApiConfig getEffectiveApiConfig({String? specificConfigId}) =>
      (super.noSuchMethod(
            Invocation.method(#getEffectiveApiConfig, [], {
              #specificConfigId: specificConfigId,
            }),
            returnValue: _FakeApiConfig_9(
              this,
              Invocation.method(#getEffectiveApiConfig, [], {
                #specificConfigId: specificConfigId,
              }),
            ),
          )
          as _i6.ApiConfig);

  @override
  _i10.Future<void> calculateAndStoreTokenCount() =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndStoreTokenCount, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> updateContextDebugInfo() =>
      (super.noSuchMethod(
            Invocation.method(#updateContextDebugInfo, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> duplicateChat({
    int? upToMessageId,
    bool? asTemplate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateChat, [], {
              #upToMessageId: upToMessageId,
              #asTemplate: asTemplate,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool updateShouldNotify(
    _i5.ChatScreenState? old,
    _i5.ChatScreenState? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i13.RemoveListener addListener(
    _i13.Listener<_i5.ChatScreenState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i13.RemoveListener);

  @override
  void init(_i14.SharedPreferences? prefs) => super.noSuchMethod(
    Invocation.method(#init, [prefs]),
    returnValueForMissingStub: null,
  );

  @override
  void showTopMessage(
    String? text, {
    _i15.Color? backgroundColor,
    Duration? duration = const Duration(seconds: 3),
  }) => super.noSuchMethod(
    Invocation.method(
      #showTopMessage,
      [text],
      {#backgroundColor: backgroundColor, #duration: duration},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void clearTopMessage() => super.noSuchMethod(
    Invocation.method(#clearTopMessage, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleOutputMode() => super.noSuchMethod(
    Invocation.method(#toggleOutputMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleBubbleTransparency() => super.noSuchMethod(
    Invocation.method(#toggleBubbleTransparency, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleBubbleWidthMode() => super.noSuchMethod(
    Invocation.method(#toggleBubbleWidthMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMessageListHeightMode() => super.noSuchMethod(
    Invocation.method(#toggleMessageListHeightMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleHighlightQuotes() => super.noSuchMethod(
    Invocation.method(#toggleHighlightQuotes, []),
    returnValueForMissingStub: null,
  );

  @override
  void setMessageListHeightMode(bool? isHalfHeight) => super.noSuchMethod(
    Invocation.method(#setMessageListHeightMode, [isHalfHeight]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleImageGenerationMode() => super.noSuchMethod(
    Invocation.method(#toggleImageGenerationMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void startUpdateTimer() => super.noSuchMethod(
    Invocation.method(#startUpdateTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopUpdateTimer() => super.noSuchMethod(
    Invocation.method(#stopUpdateTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearHelpMeReplySuggestions() => super.noSuchMethod(
    Invocation.method(#clearHelpMeReplySuggestions, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> deleteMessage(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> editMessage(
    int? messageId, {
    String? newText,
    List<_i6.MessagePart>? newParts,
    _i6.Message? updatedMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #editMessage,
              [messageId],
              {
                #newText: newText,
                #newParts: newParts,
                #updatedMessage: updatedMessage,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> leaveChat() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChat, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cloneChatAsTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#cloneChatAsTemplate, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int?> cloneChatAsNew() =>
      (super.noSuchMethod(
            Invocation.method(#cloneChatAsNew, []),
            returnValue: _i10.Future<int?>.value(),
          )
          as _i10.Future<int?>);

  @override
  _i10.Future<int?> insertMessage(int? index, _i6.MessageRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#insertMessage, [index, role]),
            returnValue: _i10.Future<int?>.value(),
          )
          as _i10.Future<int?>);

  @override
  _i10.Future<void> runAsyncProcessingTasks(_i6.Message? modelMessage) =>
      (super.noSuchMethod(
            Invocation.method(#runAsyncProcessingTasks, [modelMessage]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i6.Message> getFinalProcessedMessage(
    _i6.Chat? chat,
    _i6.Message? initialMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFinalProcessedMessage, [
              chat,
              initialMessage,
            ]),
            returnValue: _i10.Future<_i6.Message>.value(
              _FakeMessage_10(
                this,
                Invocation.method(#getFinalProcessedMessage, [
                  chat,
                  initialMessage,
                ]),
              ),
            ),
          )
          as _i10.Future<_i6.Message>);

  @override
  _i10.Future<void> regenerateResponse(_i6.Message? userMessage) =>
      (super.noSuchMethod(
            Invocation.method(#regenerateResponse, [userMessage]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> continueGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#continueGeneration, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendMessage({
    List<_i6.MessagePart>? userParts,
    _i6.Message? userMessage,
    bool? isRegeneration = false,
    bool? isContinuation = false,
    String? promptOverride,
    int? messageToUpdateId,
    String? apiConfigIdOverride,
    bool? forceNonStreaming = false,
    bool? requestThoughts = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #userParts: userParts,
              #userMessage: userMessage,
              #isRegeneration: isRegeneration,
              #isContinuation: isContinuation,
              #promptOverride: promptOverride,
              #messageToUpdateId: messageToUpdateId,
              #apiConfigIdOverride: apiConfigIdOverride,
              #forceNonStreaming: forceNonStreaming,
              #requestThoughts: requestThoughts,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#cancelGeneration, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> generateHelpMeReply({
    dynamic Function(List<String>)? onSuggestionsReady,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateHelpMeReply, [], {
              #onSuggestionsReady: onSuggestionsReady,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> executeSpecialAction({
    required String? prompt,
    required _i6.ApiConfig? apiConfig,
    required _i16.SpecialActionType? actionType,
    required _i6.Message? targetMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeSpecialAction, [], {
              #prompt: prompt,
              #apiConfig: apiConfig,
              #actionType: actionType,
              #targetMessage: targetMessage,
            }),
            returnValue: _i10.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#executeSpecialAction, [], {
                  #prompt: prompt,
                  #apiConfig: apiConfig,
                  #actionType: actionType,
                  #targetMessage: targetMessage,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> manuallySummarizeHistory() =>
      (super.noSuchMethod(
            Invocation.method(#manuallySummarizeHistory, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> executeSecondaryXmlGeneration(
    _i6.Chat? chat,
    _i6.Message? targetMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeSecondaryXmlGeneration, [
              chat,
              targetMessage,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i6.Chat?> executePreprocessing(_i6.Chat? chat) =>
      (super.noSuchMethod(
            Invocation.method(#executePreprocessing, [chat]),
            returnValue: _i10.Future<_i6.Chat?>.value(),
          )
          as _i10.Future<_i6.Chat?>);

  @override
  _i10.Future<String> summarizeMessages(
    List<_i6.Message>? messages,
    String? existingSummary, {
    List<_i6.Message>? followingMessages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #summarizeMessages,
              [messages, existingSummary],
              {#followingMessages: followingMessages},
            ),
            returnValue: _i10.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #summarizeMessages,
                  [messages, existingSummary],
                  {#followingMessages: followingMessages},
                ),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> executeAutoTitleGeneration(
    _i6.Chat? chat,
    _i6.Message? currentModelMessage,
    List<_i6.Message>? allMessages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeAutoTitleGeneration, [
              chat,
              currentModelMessage,
              allMessages,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> generateImage(_i6.Message? userMessage) =>
      (super.noSuchMethod(
            Invocation.method(#generateImage, [userMessage]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> resumeGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#resumeGeneration, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void changeHelpMeReplyPage(int? delta) => super.noSuchMethod(
    Invocation.method(#changeHelpMeReplyPage, [delta]),
    returnValueForMissingStub: null,
  );
}
