name: gemini_chat_app
description: A Flutter Gemini Chat Application.
publish_to: 'none' # Prevent accidental publishing

version: 2.1.0+10

environment:
  sdk: '>=3.0.0 <4.0.0' # Use appropriate SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7 # Check pub.dev for latest version
  flutter_riverpod: ^2.4.9    # Check pub.dev for latest version
  flutter_secure_storage: ^10.0.0-beta.4 # Check pub.dev for latest version
  shared_preferences: ^2.5.3  # Check pub.dev for latest version
  uuid: ^4.3.3             # Check pub.dev for latest version
  intl: ^0.20.2              # Check pub.dev for latest version, adjust based on Flutter version
  flutter_markdown: ^0.7.7    # 更新版本约束以允许最新版本
  image_picker: ^1.0.7        # 添加 image_picker 依赖
  logging: ^1.2.0             # 添加 logging 依赖
  collection: ^1.19.1
  flutter_gemini: ^3.0.0
  provider: ^6.1.5
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.22 # For native platforms
  path_provider: ^2.1.3 # For finding the database path
  path: ^1.9.0 # For path manipulation
  drift_sqflite: ^2.0.1 # Drift sqflite for mobile if needed later (alternative to sqlite3_flutter_libs)
  # For web, drift uses sql.js automatically, no direct dependency needed unless specific config
  go_router: ^16.0.0
  xml: ^6.5.0
  reorderable_grid_view: ^2.2.8
  image: ^4.1.7             # 用于图像处理 (生成、读写)
  file_picker: ^10.1.2       # 用于选择文件 (导入)
  permission_handler: ^12.0.0+1 # 用于请求存储权限
  exif: ^3.2.0              # 用于读写图片 EXIF 元数据
  share_plus: ^11.0.0       # (可选) 用于分享导出的文件 (已升级以解决依赖冲突)
  dio: ^5.4.0               # 添加 dio 用于 HTTP 请求
  mime: ^2.0.0              # 用于查找 Mime 类型
  tiktoken: ^1.0.3          # For OpenAI token counting
  archive: ^4.0.7           # For creating ZIP archives
  # For real persistence (replace in-memory history):
  # hive: ^latest
  # hive_flutter: ^latest


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^7.5.6 # Update analyzer
  build_runner: ^2.4.9 # Flutter 代码生成工具
  drift_dev: ^2.26.0 # Drift code generator
  # For Hive generation (if used):
  # build_runner: ^latest
  # hive_generator: ^latest
  flutter_launcher_icons: ^0.14.3 # 添加图标生成器依赖

flutter_launcher_icons:
  android: true # 为 Android 生成图标
  ios: true     # 为 iOS 生成图标
  windows: # 为 Windows 生成图标
    generate: true
  macos: # 为 macOS 生成图标
    generate: true
  web: # 为 Web 生成图标
    generate: true
  image_path: "assets/icon/icon.png" # 指定图标文件的路径

flutter:
  uses-material-design: true
