// lib/src/gemini/models/file.dart


// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

/// The source of the File.
enum Source {
  /// The default value. This value is used if the source is omitted.
  unspecified('SOURCE_UNSPECIFIED'),

  /// Indicates the file is uploaded by the user.
  uploaded('UPLOADED'),

  /// Indicates the file is generated by Google.
  generated('GENERATED');

  const Source(this.value);
  final String value;
}

/// Metadata for a video file.
class VideoFileMetadata {
  /// The duration of the video.
  final Duration? videoDuration;

  const VideoFileMetadata({this.videoDuration});

  factory VideoFileMetadata.fromJson(Map<String, dynamic> json) {
    final durationString = json['videoDuration'] as String?;
    Duration? duration;
    if (durationString != null) {
      final seconds = double.tryParse(durationString.replaceAll('s', ''));
      if (seconds != null) {
        duration = Duration(microseconds: (seconds * 1000000).toInt());
      }
    }
    return VideoFileMetadata(videoDuration: duration);
  }
}

/// States for the lifecycle of a File.
enum FileState {
  unspecified('STATE_UNSPECIFIED'),
  processing('PROCESSING'),
  active('ACTIVE'),
  failed('FAILED');

  const FileState(this.value);
  final String value;
}

/// A file uploaded to the Gemini API.
class File {
  final String name;
  final String uri;
  final String mimeType;
  final int sizeBytes;
  final DateTime createTime;
  final DateTime updateTime;
  final DateTime? expirationTime;
  final String sha256Hash;
  final String displayName;
  final String? downloadUri;
  final FileState state;
  final Map<String, dynamic>? error;
  final Source? source;
  final VideoFileMetadata? videoMetadata;

  const File({
    required this.name,
    required this.uri,
    required this.mimeType,
    required this.sizeBytes,
    required this.createTime,
    required this.updateTime,
    this.expirationTime,
    required this.sha256Hash,
    required this.displayName,
    this.downloadUri,
    required this.state,
    this.error,
    this.source,
    this.videoMetadata,
  });

  factory File.fromJson(Map<String, dynamic> json) {
    return File(
      name: json['name'],
      uri: json['uri'],
      mimeType: json['mimeType'],
      sizeBytes: int.tryParse(json['sizeBytes']?.toString() ?? '0') ?? 0,
      createTime: DateTime.parse(json['createTime']),
      updateTime: DateTime.parse(json['updateTime']),
      expirationTime: json['expirationTime'] != null
          ? DateTime.parse(json['expirationTime'])
          : null,
      sha256Hash: json['sha256Hash'],
      displayName: json['displayName'] ?? '',
      downloadUri: json['downloadUri'],
      state: json['state'] != null
          ? FileState.values.firstWhere((e) => e.value == json['state'],
              orElse: () => FileState.unspecified)
          : FileState.unspecified,
      error: json['error'],
      source: json['source'] != null
          ? Source.values.firstWhere((e) => e.value == json['source'],
              orElse: () => Source.unspecified)
          : null,
      videoMetadata: json['videoMetadata'] != null
          ? VideoFileMetadata.fromJson(json['videoMetadata'])
          : null,
    );
  }
}